### ISSUE TITLE
getting the content of the barcodes found

### ISSUE THREAD

**Issue by haemi** [hansemannn/iOS11-QR-Code-Example#2]
I do get the content currently for QR Codes like this:

```
if let desc = barcode.barcodeDescriptor as? CIQRCodeDescriptor, let bytes = desc.bytes, let content = String(data: bytes, encoding: .utf8) {
    self?.resultLabel.text = content
}
```

but the barcodeDescriptor is nil for other Barcode types (e.g. `symbology` = `VNBarcodeSymbologyDataMatrix`) - am I missing something or is this not implemented by Apple yet?

**Comment by hansemannn** [comment]
See #3 that should fix this as well.
